name: Unit and E2E Tests Workflow

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/pull_request_template.md"
      - ".github/workflows/deploy.yml"
      - "README.md"
      - "example/README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Install dependencies for server
        run: npm ci
        working-directory: ./example

      - name: Install Wait On for Server
        run: npm install -g wait-on

      - name: Start Server for E2E Tests
        run: |
          npm run dev &
          echo $! > server.pid
        working-directory: ./example

      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3000
        working-directory: ./example

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Stop Server
        run: kill $(cat server.pid)
        working-directory: ./example

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2
